/*
 * CharVstack-API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"fmt"
	sw "github.com/CharVstack/CharV-backend/v1/go"
	"github.com/joho/godotenv"
	"log"
	"os"
)

func init() {
	err := godotenv.Load("./.env")
	if err != nil {
		fmt.Printf(err.Error())
		os.Exit(2)
	}
}

func main() {
	log.Printf("Server started")

	router := sw.NewRouter()

	log.Fatal(router.Run(":8080"))
}
