/*
 * CharVstack-API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"fmt"
	"log"
	"os"

	"github.com/CharVstack/CharV-backend/handler"
	"github.com/CharVstack/CharV-backend/openapi/v1"
	"github.com/gin-gonic/gin"
	"github.com/joho/godotenv"
)

func init() {
	err := godotenv.Load("./.env")
	if err != nil {
		fmt.Printf(err.Error())
		os.Exit(2)
	}
}

func main() {
	r := gin.Default()

	getHandler := handler.V1Handler{}

	router := openapi.RegisterHandlers(r, getHandler)

	log.Fatal(router.Run(":8080"))
}
