/*
 * CharVstack-API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"errors"
	"fmt"
	"io/fs"
	"log"
	"os"
	"time"

	"github.com/CharVstack/CharV-backend/adapters"
	"github.com/CharVstack/CharV-backend/handler"
	middleware "github.com/deepmap/oapi-codegen/pkg/gin-middleware"
	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	"github.com/joho/godotenv"
)

func init() {
	err := godotenv.Load("./.env")
	if err != nil {
		fmt.Printf(err.Error())
		os.Exit(2)
	}

	storageDirEnv := os.Getenv("STORAGE_DIR")
	_, err = os.ReadDir(storageDirEnv)
	if err != nil && errors.Is(err, fs.ErrNotExist) {
		log.Fatal(err)
	}
}

func main() {
	r := gin.Default()

	swagger, err := adapters.GetSwagger()
	if err != nil {
		log.Fatal(err)
	}
	r.Use(middleware.OapiRequestValidator(swagger))

	r.Use(cors.New(cors.Config{
		AllowOrigins: []string{
			os.Getenv("ORIGIN_URI"),
		},
		AllowMethods: []string{
			"GET",
			"POST",
			"OPTIONS",
		},
		AllowHeaders: []string{
			"Content-Type",
		},
		AllowCredentials: false,
		MaxAge:           24 * time.Hour,
	}))

	getHandler := handler.V1Handler{}

	router := adapters.RegisterHandlers(r, getHandler)

	if err := router.Run(":8080"); err != nil {
		log.Fatal(err)
	}
}
