/*
 * Sample API
 *
 * A sample API to illustrate OpenAPI concepts
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// ListGet -
func ListGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
