/*
 * CharVstack-API
 *
 * A sample API to illustrate OpenAPI concepts
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeleteVmVmId - VMの削除
func DeleteVmVmId(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetApiV1Vm - VM一覧の取得
func GetApiV1Vm(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetVmVmId - VMの情報
func GetVmVmId(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PatchVmsVmId - VMの更新
func PatchVmsVmId(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostApiV1Vm - VMの作成
func PostApiV1Vm(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
