/*
 * CharVstack-API
 *
 * A sample API to illustrate OpenAPI concepts
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GetApiV1Vm200ResponseVmsInner struct {
	Cpu int32 `json:"cpu,omitempty"`

	Memory int32 `json:"memory,omitempty"`

	Id string `json:"id,omitempty"`

	Name string `json:"name,omitempty"`
}
