// Package adapters provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package adapters

import (
	"github.com/CharVstack/CharV-backend/domain/models"
)

type Cpu = models.Cpu

type Devices = models.Devices

type Disk = models.Disk

type DiskDevice = models.DiskDevice

type DiskType = models.DiskType

type Host = models.Host

type Memory = models.Memory

type Metadata = models.Metadata

type StoragePool = models.StoragePool

type StoragePoolStatus = models.StoragePoolStatus

type Vm = models.Vm

type VmPowerInfo = models.VmPowerInfo

type VmPowerInfoState = models.VmPowerInfoState

type GetAllVMsList200Response = models.GetAllVMsList200Response

type GetHost200Response = models.GetHost200Response

type GetVMByVMId200Response = models.GetVMByVMId200Response

type GetVMPowerByVMId200Response = models.GetVMPowerByVMId200Response

type PatchUpdateVMByVMId200Response = models.PatchUpdateVMByVMId200Response

type PostCreateNewVM200Response = models.PostCreateNewVM200Response

type PatchUpdateVMRequest = models.PatchUpdateVMRequest

type PostChangeVMsPowerStatusByVMIdRequest = models.PostChangeVMsPowerStatusByVMIdRequest

type PostCreateNewVMRequest = models.PostCreateNewVMRequest

type PostApiV1VmsJSONBody = models.PostApiV1VmsJSONBody

type PatchApiV1VmsVmIdJSONBody = models.PatchApiV1VmsVmIdJSONBody

type PostApiV1VmsVmIdPowerJSONBody = models.PostApiV1VmsVmIdPowerJSONBody

type PostApiV1VmsVmIdPowerJSONBodyAction = models.PostApiV1VmsVmIdPowerJSONBodyAction

type PostApiV1VmsJSONRequestBody = models.PostApiV1VmsJSONRequestBody

type PatchApiV1VmsVmIdJSONRequestBody = models.PatchApiV1VmsVmIdJSONRequestBody

type PostApiV1VmsVmIdPowerJSONRequestBody = models.PostApiV1VmsVmIdPowerJSONRequestBody
