// Package adapters provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.2 DO NOT EDIT.
package adapters

import (
	"github.com/CharVstack/CharV-backend/domain/models"
)

type Cpu = models.Cpu

type Devices = models.Devices

type Disk = models.Disk

type DiskDevice = models.DiskDevice

type DiskType = models.DiskType

type Host = models.Host

type Memory = models.Memory

type Metadata = models.Metadata

type StoragePool = models.StoragePool

type StoragePoolStatus = models.StoragePoolStatus

type Vm = models.Vm

type VmStatus = models.VmStatus

type VmPowerInfo = models.VmPowerInfo

type VmPowerInfoState = models.VmPowerInfoState

type GetAllVMsList200Response = models.GetAllVMsList200Response

type GetHost200Response = models.GetHost200Response

type GetVMByVMId200Response = models.GetVMByVMId200Response

type GetVMPowerByVMId200Response = models.GetVMPowerByVMId200Response

type PatchUpdateVMByVMId200Response = models.PatchUpdateVMByVMId200Response

type PostCreateNewVM200Response = models.PostCreateNewVM200Response

type PostApiV1VmsJSONBody = models.PostApiV1VmsJSONBody

type PatchApiV1VmsVmIdJSONBody = models.PatchApiV1VmsVmIdJSONBody

type PostApiV1VmsVmIdPowerActionParams = models.PostApiV1VmsVmIdPowerActionParams

type PostApiV1VmsVmIdPowerActionParamsAction = models.PostApiV1VmsVmIdPowerActionParamsAction

type PostApiV1VmsJSONRequestBody = models.PostApiV1VmsJSONRequestBody

type PatchApiV1VmsVmIdJSONRequestBody = models.PatchApiV1VmsVmIdJSONRequestBody

type GetApiV1VmsVmIdPowerJSONRequestBody = models.VmPowerInfo
