// Code generated by repackage.awk DO NOT EDIT.
package models

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// Defines values for DiskDevice.
const (
	DiskDeviceCdrom   DiskDevice = "cdrom"
	DiskDeviceDisk    DiskDevice = "disk"
	DiskDeviceUnknown DiskDevice = "unknown"
)

// Defines values for DiskType.
const (
	DiskTypeQcow2   DiskType = "qcow2"
	DiskTypeUnknown DiskType = "unknown"
)

// Defines values for StoragePoolStatus.
const (
	ACTIVE StoragePoolStatus = "ACTIVE"
	ERROR  StoragePoolStatus = "ERROR"
)

// Defines values for VmPowerInfoState.
const (
	RUNNING  VmPowerInfoState = "RUNNING"
	SHUTDOWN VmPowerInfoState = "SHUTDOWN"
	UNKNOWN  VmPowerInfoState = "UNKNOWN"
)

// Defines values for PostApiV1VmsVmIdPowerActionParamsAction.
const (
	Reboot   PostApiV1VmsVmIdPowerActionParamsAction = "reboot"
	Reset    PostApiV1VmsVmIdPowerActionParamsAction = "reset"
	Shutdown PostApiV1VmsVmIdPowerActionParamsAction = "shutdown"
	Start    PostApiV1VmsVmIdPowerActionParamsAction = "start"
)

// Cpu ホストのCPU情報
type Cpu struct {
	Counts  int     `json:"counts"`
	Percent float64 `json:"percent"`
}

// Devices defines model for Devices.
type Devices struct {
	Disk []Disk `json:"disk"`
}

// Disk defines model for Disk.
type Disk struct {
	Device DiskDevice `json:"device"`
	Name   string     `json:"name"`
	Pool   string     `json:"pool"`
	Type   DiskType   `json:"type"`
}

// DiskDevice defines model for Disk.Device.
type DiskDevice string

// DiskType defines model for Disk.Type.
type DiskType string

// Host defines model for Host.
type Host struct {
	// Cpu ホストのCPU情報
	Cpu Cpu `json:"cpu"`

	// Memory ホストのメモリ情報
	Memory       Memory        `json:"memory"`
	StoragePools []StoragePool `json:"storage_pools"`
}

// Memory ホストのメモリ情報
type Memory struct {
	Free    uint64  `json:"free"`
	Percent float64 `json:"percent"`
	Total   uint64  `json:"total"`
	Used    uint64  `json:"used"`
}

// Metadata defines model for Metadata.
type Metadata struct {
	ApiVersion string             `json:"api_version"`
	Id         openapi_types.UUID `json:"id"`
}

// StoragePool ホストが持つストレージプールの情報
type StoragePool struct {
	Name      string            `json:"name"`
	Path      string            `json:"path"`
	Status    StoragePoolStatus `json:"status"`
	TotalSize uint64            `json:"total_size"`
	UsedSize  uint64            `json:"used_size"`
}

// StoragePoolStatus defines model for StoragePool.Status.
type StoragePoolStatus string

// Vm 仮想マシンを表すモデル
type Vm struct {
	Cpu      int      `json:"cpu"`
	Devices  Devices  `json:"devices"`
	Memory   uint64   `json:"memory"`
	Metadata Metadata `json:"metadata"`
	Name     string   `json:"name"`
}

// VmPowerInfo defines model for VmPowerInfo.
type VmPowerInfo struct {
	CleanPowerOff bool             `json:"clean_power_off"`
	State         VmPowerInfoState `json:"state"`
}

// VmPowerInfoState defines model for VmPowerInfo.State.
type VmPowerInfoState string

// GetAllVMsList200Response defines model for GetAllVMsList200Response.
type GetAllVMsList200Response struct {
	Vms []Vm `json:"vms"`
}

// GetHost200Response defines model for GetHost200Response.
type GetHost200Response struct {
	Host Host `json:"host"`
}

// GetVMByVMId200Response defines model for GetVMByVMId200Response.
type GetVMByVMId200Response struct {
	// Vm 仮想マシンを表すモデル
	Vm Vm `json:"vm"`
}

// GetVMPowerByVMId200Response defines model for GetVMPowerByVMId200Response.
type GetVMPowerByVMId200Response struct {
	VmPower VmPowerInfo `json:"vm_power"`
}

// PatchUpdateVMByVMId200Response defines model for PatchUpdateVMByVMId200Response.
type PatchUpdateVMByVMId200Response struct {
	// Vm 仮想マシンを表すモデル
	Vm Vm `json:"vm"`
}

// PostCreateNewVM200Response defines model for PostCreateNewVM200Response.
type PostCreateNewVM200Response struct {
	// Vm 仮想マシンを表すモデル
	Vm Vm `json:"vm"`
}

// PatchUpdateVMRequest defines model for PatchUpdateVMRequest.
type PatchUpdateVMRequest struct {
	Cpu    int    `json:"cpu"`
	Memory int    `json:"memory"`
	Name   string `json:"name"`
}

// PostCreateNewVMRequest defines model for PostCreateNewVMRequest.
type PostCreateNewVMRequest struct {
	Cpu    int    `json:"cpu"`
	Memory int    `json:"memory"`
	Name   string `json:"name"`
}

// PostApiV1VmsJSONBody defines parameters for PostApiV1Vms.
type PostApiV1VmsJSONBody struct {
	Cpu    int    `json:"cpu"`
	Memory uint64 `json:"memory"`
	Name   string `json:"name"`
}

// PatchApiV1VmsVmIdJSONBody defines parameters for PatchApiV1VmsVmId.
type PatchApiV1VmsVmIdJSONBody struct {
	Cpu    *int    `json:"cpu,omitempty"`
	Memory *uint64 `json:"memory,omitempty"`
	Name   *string `json:"name,omitempty"`
}

// PostApiV1VmsVmIdPowerActionParams defines parameters for PostApiV1VmsVmIdPowerAction.
type PostApiV1VmsVmIdPowerActionParams struct {
	Action *PostApiV1VmsVmIdPowerActionParamsAction `form:"action,omitempty" json:"action,omitempty"`
}

// PostApiV1VmsVmIdPowerActionParamsAction defines parameters for PostApiV1VmsVmIdPowerAction.
type PostApiV1VmsVmIdPowerActionParamsAction string

// PostApiV1VmsJSONRequestBody defines body for PostApiV1Vms for application/json ContentType.
type PostApiV1VmsJSONRequestBody PostApiV1VmsJSONBody

// PatchApiV1VmsVmIdJSONRequestBody defines body for PatchApiV1VmsVmId for application/json ContentType.
type PatchApiV1VmsVmIdJSONRequestBody PatchApiV1VmsVmIdJSONBody
