// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package models

// ホストのCPU情報
type Cpu struct {
	Counts  int         `json:"counts"`
	Percent TypeFloat64 `json:"percent"`
}

// ホストのメモリ情報
type Memory struct {
	Free        TypeUint64  `json:"free"`
	Total       TypeUint64  `json:"total"`
	Used        TypeUint64  `json:"used"`
	UsedPercent TypeFloat64 `json:"used_percent"`
}

// ホストが持つストレージプールの情報
type StoragePool struct {
	Name      string     `json:"name"`
	Path      string     `json:"path"`
	Status    string     `json:"status"`
	TotalSize TypeUint64 `json:"total_size"`
	UsedSize  TypeUint64 `json:"used_size"`
}

// 仮想マシンを表すモデル
type Vm struct {
	Devices struct {
		Disk []struct {
			Path string `json:"path"`
			Type string `json:"type"`
		} `json:"disk"`
	} `json:"devices"`
	Memory   int `json:"memory"`
	Metadata struct {
		ApiVersion string `json:"api_version"`
		Id         string `json:"id"`
	} `json:"metadata"`
	Name string `json:"name"`
	Vcpu int    `json:"vcpu"`
}

// TypeFloat64 defines model for type_float64.
type TypeFloat64 float64

// TypeUint64 defines model for type_uint64.
type TypeUint64 uint64

// PostApiV1VmsJSONBody defines parameters for PostApiV1Vms.
type PostApiV1VmsJSONBody struct {
	Memory int    `json:"memory"`
	Name   string `json:"name"`
	Vcpu   int    `json:"vcpu"`
}

// PatchApiV1VmsVmIdJSONBody defines parameters for PatchApiV1VmsVmId.
type PatchApiV1VmsVmIdJSONBody struct {
	Memory *int    `json:"memory,omitempty"`
	Name   *string `json:"name,omitempty"`
	Vcpu   *int    `json:"vcpu,omitempty"`
}

// PostApiV1VmsJSONRequestBody defines body for PostApiV1Vms for application/json ContentType.
type PostApiV1VmsJSONRequestBody PostApiV1VmsJSONBody

// PatchApiV1VmsVmIdJSONRequestBody defines body for PatchApiV1VmsVmId for application/json ContentType.
type PatchApiV1VmsVmIdJSONRequestBody PatchApiV1VmsVmIdJSONBody
