/*
 * CharVstack-API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// GetApiV1Vms - Get all VMs list
func GetApiV1Vms(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetApiV1VmsVmId - Get a VM
func GetApiV1VmsVmId(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PatchApiV1VmsVmId - Update a VM
func PatchApiV1VmsVmId(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostApiV1Vms - Create a new VM
func PostApiV1Vms(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
