/*
 * CharVstack-API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type VmDevicesDiskInner struct {
	Type string `json:"type,omitempty"`

	Path string `json:"path,omitempty"`
}
