/*
 * CharVstack-API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PatchApiV1VmsVmIdRequest struct {
	Name string `json:"name,omitempty"`

	Memory int32 `json:"memory,omitempty"`

	Vcpu int32 `json:"vcpu,omitempty"`
}
