/*
 * CharVstack-API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type StoragePool struct {
	Name string `json:"name,omitempty"`

	TotalSize int32 `json:"total_size,omitempty"`

	UsedSize int32 `json:"used_size,omitempty"`

	Path string `json:"path,omitempty"`

	Status string `json:"status,omitempty"`
}
