/*
 * CharVstack-API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package oldopenapi

type Memory struct {
	Total uint64 `json:"total,omitempty"`

	Used uint64 `json:"used,omitempty"`

	Free uint64 `json:"free,omitempty"`

	UsedPercent float64 `json:"used_percent,omitempty"`
}
