/*
 * CharVstack-API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package oldopenapi

type VmDevices struct {
	Disk []VmDevicesDiskInner `json:"disk,omitempty"`
}
