/*
 * CharVstack-API
 *
 * A sample API to illustrate OpenAPI concepts
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package oldopenapi

type GetApiV1Vm200Response struct {
	Vms []GetApiV1Vm200ResponseVmsInner `json:"vms,omitempty"`

	Total int32 `json:"total,omitempty"`
}
