/*
 * CharVstack-API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Memory struct {
	Total int32 `json:"total,omitempty"`

	Used int32 `json:"used,omitempty"`

	Free int32 `json:"free,omitempty"`

	UsedPercent float32 `json:"used_percent,omitempty"`
}
