/*
 * CharVstack-API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GetApiV1Host200Response struct {
	Cpu int32 `json:"cpu,omitempty"`

	Memory int32 `json:"memory,omitempty"`

	StoragePools []StoragePool `json:"storage_pools,omitempty"`
}
