/*
 * CharVstack-API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Cpu struct {
	Cpu int `json:"cpu"`

	CpuMhz float64 `json:"cpu_mhz,omitempty"`
}
