name: Deploy Staging Environment
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    environment:
      name: staging

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: ./go.mod
          cache: true

      - name: Build
        run: |
          make build
          cp ./bin/server ~/CharV-backend/charv-backend

      - name: Set up environment
        run : ~/CharV-backend/init.sh

      - name: Restart server
        run : ssh ${{ secrets.DEPLOYMENT_USER }}@${{ secrets.DEPLOYMENT_SERVER }} systemctl restart charv@backend.service
