name: Deploy Development
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    environment:
      name: development

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: ./go.mod
          cache: true
      - name: Build
        run: make build

      - name: Set up Environment
        run : ssh ${{ secret.development_server_user }}@${{ secret.development_server_ip }} ~/CharV-backend/init.sh

      - name: Restart Server
        run : ssh ${{ secret.development_server_user }}@${{ secret.development_server_ip }} systemctl restart charv@backend.service
