name: Deploy Development
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    environment:
      name: development

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: ./go.mod
          cache: true
      - name: Build
        run: |
          make build
          cp ./bin/server ~/CharV-backend/charv-backend

      - name: Set up environment
        run : ~/CharV-backend/init.sh

      - name: Restart server
        run : ssh ${{ secrets.DEVELOPMENT_SERVER_USER }}@${{ secrets.DEVELOPMENT_SERVER_IP }} systemctl restart charv@backend.service
