name: Deploy Production Environment
on:
  create:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: ./go.mod
          cache: true

      - name: Build
        run: |
          make build
          mv bin/server bin/charv-backend

      - name: Tailscale
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: bin/charv-backend
          remote_path: /usr/local/bin/charv-backend
          remote_host: ${{ secrets.DEPLOYMENT_SERVER }}
          remote_user: ${{ secrets.DEPLOYMENT_USER }}
          remote_key: ${{ secrets.DEPLOYMENT_KEY }}

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOYMENT_SERVER }}
          username: ${{ secrets.DEPLOYMENT_USER }}
          key: ${{ secrets.DEPLOYMENT_KEY }}
          port: ${{ secrets.DEPLOYMENT_PORT }}
          script: |
            systemctl restart charv@backend.service
